name: 'Deploy App Engine'
description: 'This action allowed you publish an application to Google App Engine'
inputs:
  service-account:
    description: 'Service account file'
    required: true
  project-id:
    description: 'Project id'
    required: true
  debug:
    description: 'Debug action'
    default: false
  gae_config_path:
    description: 'Path to the yaml file'
    required: true
    default: './app.yaml'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'box'
  color: 'blue'
