on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say service count
    steps:
    - name: Deploy App Engine
      id: deploy
      uses: claudiuri/deploy-gae-action@master
      with:
        service-account:  ${{ secrets.SERVICE_ACCOUNT }}
        project-name: 'vidly-280513'
        debug: true
    # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"
