on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say service count
    steps:
    - name: Deploy App Engine
      id: deploy
      uses: claudiuri/deploy-gae-action@master
      with:
        service-account:  ${{ secrets.SERVICE_ACCOUNT }}
        project-id: ${{ secrets.PROJECT_ID }}
        debug: true