on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Example project
    steps:
    - name: Deploy App Engine
      id: deploy
      uses: etereo-io/deploy-gae-action
      with:
        service_account:  ${{ secrets.SERVICE_ACCOUNT }}
        project_id: ${{ secrets.PROJECT_ID }}
        gae_config_path: './app.yaml'
        debug: true
        no_cache: false
        dispatch_yaml: ''